from .defaults import *

DEBUG = True

ALLOWED_HOSTS = []

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_SECONDS = None
SECURE_HSTS_PRELOAD = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
CORS_REPLACE_HTTPS_REFERER      = False
HOST_SCHEME                     = "http://"