/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubmissionsSubmissionIdImport } from './routes/_authenticated/submissions.$submissionId'
import { Route as AuthenticatedSectionsSectionIdImport } from './routes/_authenticated/sections.$sectionId'
import { Route as AuthenticatedAssignmentsAssignmentIdImport } from './routes/_authenticated/assignments.$assignmentId'
import { Route as AuthenticatedCoursesCourseIdIndexImport } from './routes/_authenticated/courses.$courseId.index'
import { Route as AuthenticatedCoursesCourseIdStudentsStudentIdImport } from './routes/_authenticated/courses.$courseId.students.$studentId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSubmissionsSubmissionIdRoute =
  AuthenticatedSubmissionsSubmissionIdImport.update({
    path: '/submissions/$submissionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSectionsSectionIdRoute =
  AuthenticatedSectionsSectionIdImport.update({
    path: '/sections/$sectionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAssignmentsAssignmentIdRoute =
  AuthenticatedAssignmentsAssignmentIdImport.update({
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCoursesCourseIdIndexRoute =
  AuthenticatedCoursesCourseIdIndexImport.update({
    path: '/courses/$courseId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCoursesCourseIdStudentsStudentIdRoute =
  AuthenticatedCoursesCourseIdStudentsStudentIdImport.update({
    path: '/courses/$courseId/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/assignments/$assignmentId': {
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/sections/$sectionId': {
      preLoaderRoute: typeof AuthenticatedSectionsSectionIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/submissions/$submissionId': {
      preLoaderRoute: typeof AuthenticatedSubmissionsSubmissionIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/courses/$courseId/': {
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/courses/$courseId/students/$studentId': {
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdStudentsStudentIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedIndexRoute,
    AuthenticatedAssignmentsAssignmentIdRoute,
    AuthenticatedSectionsSectionIdRoute,
    AuthenticatedSubmissionsSubmissionIdRoute,
    AuthenticatedCoursesCourseIdIndexRoute,
    AuthenticatedCoursesCourseIdStudentsStudentIdRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
