name: Python Package using Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    name: Build and lint with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Activate Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: django-tf
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        auto-activate-base: false
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list

      
        
